paths:
  uploads: public/uploads
  static: public
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
    url: /[full_slug]/
    disable_url: false
    _enabled_editors:
      - visual
    _inputs:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: src/content/blog
    icon: event_available
    disable_url: false
    _enabled_editors:
      - visual
    _inputs:
      $.draft:
        type: switch
        cascade: true
      $.image.alt:
        type: textarea
        options:
          empty_type:
          show_count:
          required: true
          required_message:
          min_length:
          min_length_message:
          max_length:
          max_length_message:
          pattern:
          pattern_message:
        cascade: true
      $.publishDate:
        type: datetime
        cascade: true
      $.tags:
        type: multiselect
        options:
          allow_create: true
          allow_empty: true
          values:
          value_key:
          preview:
          picker_preview:
          view:
          picker_view:
          required:
          required_message:
          min_length:
          min_length_message:
          max_length:
          max_length_message:
          pattern:
          pattern_message:
          empty_type:
          min_items:
          min_items_message:
          max_items:
          max_items_message:
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  team:
    path: src/content/team
    icon: emoji_people
    disable_url: false
    preview:
      text:
      subtext:
        - key: title
      icon:
      icon_color:
      icon_background_color:
      image:
      metadata:
      gallery:
        text:
        icon:
        icon_color:
        icon_background_color:
        background_color:
        image:
          - key: avatar.src
        fit:
    disable_add: false
    disable_add_folder: true
    disable_file_actions: true

data_config:
  boxIcons:
    path: data/box-icons.json
  simpleIcons:
    path: data/simple-icons.json

_inputs:
  type:
    hidden: true
  $.image.src:
    type: image
    cascade: true
  $.layout:
    hidden: true
    cascade: true
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false

# _structures:
#   content_blocks:
#     values:
#       - label: Hero
#         value:
#           type: hero
#           heading: 
#           content: 
#           color: "#ffffff"
#           image: /images/hero.png
#       - label: Features
#         value:
#           type: features
#           heading: 
#           description: 
#           features: []
#         _inputs:
#           features:
#             type: array
#             options:
#               structures: _structures.feature
#         _structures:
#           feature:
#             values:
#               - value:
#                   title: 
#                   description: 
#                   icon: 
#                 _inputs:
#                   icon:
#                     type: select
#                     options:
#                       values: data.boxIcons
#       - label: Logos
#         value:
#           type: logos
#           heading: 
#           icons: []
#         _inputs:
#           icons:
#             type: multiselect
#             options:
#               values: data.simpleIcons
#       - label: CTA
#         value:
#           type: cta
#           heading: 
#           description: 
#           buttonText: 
#           buttonLink: "#"